- name: Copy backup script to server.
  template:
    src: backup-remote-fetch.sh.j2
    dest: "{{ backup_path }}/backup-remote-fetch.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0744

- name: Configure backup remote fetch cron job.
  cron:
    name: "Backup remote fetch cron job"
    minute: "{{ backup_remote_fetch_backup_minute }}"
    hour: "{{ backup_remote_fetch_backup_hour }}"
    day: "{{ backup_remote_fetch_backup_day }}"
    user: "{{ backup_user }}"
    job: "{{ backup_path }}/backup-remote-fetch.sh"
    state: "{{ backup_remote_fetch_backup_cron_job_state }}"
