- name: Ensure backup folder exists.
  file:
    path: "{{ backup_path }}"
    state: directory
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0775

- name: Copy backup script to server.
  template:
    src: backup.sh.j2
    dest: "{{ backup_path }}/backup.sh"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0744

- name: Copy excludes file to server.
  template:
    src: backup-exclude.txt.j2
    dest: "{{ backup_path }}/backup-exclude.txt"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0644

- name: Configure backup cron job.
  cron:
    name: "Backup cron job"
    minute: "{{ backup_minute }}"
    hour: "{{ backup_hour }}"
    day: "{{ backup_day }}"
    user: "{{ backup_user }}"
    job: "{{ backup_path }}/backup.sh"
    state: "{{ backup_cron_job_state }}"

- name: Include Remote Backup Fetch
  ansible.builtin.include_tasks: backup-remote-fetch.yml
  when: backup_remote_fetch
